plugins:
  sevilla_news_enabled:
    client: true
    default: true

  sevilla_news_category_id:
    client: false
    type: category
    default: ""

  sevilla_news_azure_translator_key:
    client: false
    secret: true
    default: ""

  sevilla_news_azure_translator_region:
    client: false
    default: ""

  sevilla_news_articles_per_source:
    client: false
    default: 5
    min: 1
    max: 15

  sevilla_news_interval_hours:
    client: false
    default: 3
    min: 1
    max: 24

  sevilla_news_new_topic_per_update:
    client: false
    default: false

  sevilla_news_headline_in_title:
    client: false
    default: true
